name: Hellowworld workflow

on: 
push:
		branches:
			- main
		pull-request:
			branches:
				- main
		workflow_dispatch:

jobs:
	hello:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v2
			- name: Hello world
        run: echo "Hello world"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye world
        run: echo "Goodbye world"
        shell: bash
