name: create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create Comment with gh api
        run: |
          gh api -X POST \
            http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment but fromthe API call not action
            '
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZTION: ${{ github.event.organization.login }}
            REPOSITORY: ${{ gihub.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
